// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebApi.Models;

public partial class VwMyDepartCourse
{
    public int CourseId { get; set; }

    public string? Title { get; set; }

    public int Credits { get; set; }

    public string? DepartmentName { get; set; }
}